name: Security Check

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2

    - name: Run Composer install
      run: composer install --working-dir=like-button-plugin

    - name: Install PHP_CodeSniffer
      run: composer global require "squizlabs/php_codesniffer=*"

    - name: Run Composer audit
      run: composer audit --working-dir=like-button-plugin

    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=vendor/ like-button-plugin/src/
