name: Security Check

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Change directory to repository root
      run: cd $GITHUB_WORKSPACE
      
    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2
      
    - name: Install dependencies
      run: composer install
      
    - name: Install local PHP Security Checker
      run: composer global require fabpot/local-php-security-checker
      
    - name: Run security checker
      run: php -d memory_limit=-1 $(composer global config home)/vendor/bin/local-php-security-checker --path=./composer.lock
